spring.application.name=EMS
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/emsdb
spring.datasource.username=shashankDB
spring.datasource.password=shashank123
spring.jpa.hibernate.ddl-auto=update
